### ISSUE TITLE
MacSupport

### ISSUE THREAD

**Issue by MickyD420** [cheesestringer/property-seeker#3]
**URL**
Provide the URL for the property. For example:
```
https://www.domain.com.au/...
https://www.realestate.com.au
```

**Browser**
Chrome, 

**Description**
Is Chrome for Macbook supported? I have it installed on the fiancee's macbook and unlike my PC, no cigar. Have tried developer mode on and off, clearing caches etc constantly between changing configurations? Thoughts?

**Comment by cheesestringer** [comment]
It should work on apple devices, I'll look in to this to double check though
