### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by Hoagy99** [cheesestringer/property-seeker#6]
**URL**
```
https://www.realestate.com.au/property-house-qld-pelican+waters-140625103
```

**Browser**
Chrome

**Description**
Hi I have been using this extension for a while and has stopped working for some reason. Have realestate.com.au done something to block it? I use chrome and have reinstalled it

**Comment by cheesestringer** [comment]
Thanks for reporting! This has been fixed now and you should get the update soon.

**Comment by Hoagy99** [comment]
Thanks much appreciated

Best Regards

Craig Hogg
Licensed Buyers Agent
*REBAA PIPA REIQ *
M:0404 857 580
W:www.theedgebuyers.com.au
*REIQ Awards For Excellence*
*Buyers Agent Of The Year Finalist 2020, 2021*
